-- MySQL Script generated by MySQL Workbench
-- Thu Jan 30 11:47:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `Role_ID` INT NOT NULL,
  `Role_Name` ENUM('admin', 'user') NOT NULL DEFAULT 'admin, user',
  PRIMARY KEY (`Role_ID`))
ENGINE = MRG_MyISAM
DEFAULT CHARACTER SET = gbk;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Last_Login` DATETIME NULL DEFAULT NULL,
  `Privileges_Role_ID` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`Username` ASC) VISIBLE,
  PRIMARY KEY (`User_ID`, `Privileges_Role_ID`),
  INDEX `fk_User_Privileges1_idx` (`Privileges_Role_ID` ASC) VISIBLE,
  CONSTRAINT `fk_User_Privileges1`
    FOREIGN KEY (`Privileges_Role_ID`)
    REFERENCES `mydb`.`Roles` (`Role_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organism` (
  `Organim_ID` INT NULL AUTO_INCREMENT,
  `Accession_Organism_ID` VARCHAR(45) NOT NULL,
  `Scientific_Name` VARCHAR(100) NOT NULL,
  `Common_Name` VARCHAR(100) NULL DEFAULT NULL,
  `Relevance` TEXT(200) NULL, 
  PRIMARY KEY (`Organim_ID`),
  UNIQUE INDEX `tax_id_UNIQUE` (`Organim_ID` ASC) VISIBLE,
  UNIQUE INDEX `scientific_name_UNIQUE` (`Scientific_Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Protein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Protein` (
  `Accesion_ID` VARCHAR(45) NULL,
  `Sequence` LONGTEXT NOT NULL,
  `Length` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Subcellular_Location` VARCHAR(255) NULL DEFAULT NULL,
  `Evidence` ENUM('') NOT NULL,
  `Database` VARCHAR(45) NOT NULL,
  `Organism_Organim_ID` INT NOT NULL,
  PRIMARY KEY (`Accesion_ID`, `Organism_Organim_ID`),
  INDEX `fk_Protein_Organism1_idx` (`Organism_Organim_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Protein_Organism1`
    FOREIGN KEY (`Organism_Organim_ID`)
    REFERENCES `mydb`.`Organism` (`Organim_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PTM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PTM` (
  `PTM_ID` INT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NOT NULL,
  PRIMARY KEY (`PTM_ID`),
  UNIQUE INDEX `PTM_ID_UNIQUE` (`PTM_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domain` (
  `Domain_ID` INT NULL AUTO_INCREMENT,
  `Accession_ID` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Position_Start` INT NOT NULL,
  `Position_End` INT NOT NULL,
  PRIMARY KEY (`Domain_ID`),
  UNIQUE INDEX `name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `accesion_id_UNIQUE` (`Accession_ID` ASC) VISIBLE)
ENGINE = CSV
DEFAULT CHARACTER SET = armscii8
COLLATE = armscii8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`History` (
  `History_ID` INT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Query_ID` INT NOT NULL,
  PRIMARY KEY (`History_ID`),
  UNIQUE INDEX `user_id_UNIQUE` (`User_ID` ASC) VISIBLE,
  UNIQUE INDEX `queries_UNIQUE` (`Query_ID` ASC) VISIBLE,
  CONSTRAINT `fk_History_User1`
    FOREIGN KEY (`History_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Query` (
  `Query_ID` INT NULL AUTO_INCREMENT,
  `Parameters` VARCHAR(45) NOT NULL,
  `Summary_Table` BLOB NOT NULL,
  `Graph` BLOB NOT NULL,
  `Date` DATETIME NOT NULL,
  `History_History_ID` INT NOT NULL,
  PRIMARY KEY (`Query_ID`, `History_History_ID`),
  INDEX `fk_Query_History1_idx` (`History_History_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Query_History1`
    FOREIGN KEY (`History_History_ID`)
    REFERENCES `mydb`.`History` (`History_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Query_has_Protein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Query_has_Protein` (
  `Query_Query_ID` INT NOT NULL,
  `Protein_Accesion_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Query_Query_ID`, `Protein_Accesion_ID`),
  INDEX `fk_Query_has_Protein_Protein1_idx` (`Protein_Accesion_ID` ASC) VISIBLE,
  INDEX `fk_Query_has_Protein_Query1_idx` (`Query_Query_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Query_has_Protein_Query1`
    FOREIGN KEY (`Query_Query_ID`)
    REFERENCES `mydb`.`Query` (`Query_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Query_has_Protein_Protein1`
    FOREIGN KEY (`Protein_Accesion_ID`)
    REFERENCES `mydb`.`Protein` (`Accesion_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Protein_has_PTM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Protein_has_PTM` (
  `Protein_Accesion_ID` VARCHAR(45) NOT NULL,
  `PTM_PTM_ID` INT NOT NULL,
  `Position` INT NOT NULL,
  `Residue` VARCHAR(25) NOT NULL,
  `Source` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Protein_Accesion_ID`, `PTM_PTM_ID`),
  INDEX `fk_Protein_has_PTM_PTM1_idx` (`PTM_PTM_ID` ASC) VISIBLE,
  INDEX `fk_Protein_has_PTM_Protein1_idx` (`Protein_Accesion_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Protein_has_PTM_Protein1`
    FOREIGN KEY (`Protein_Accesion_ID`)
    REFERENCES `mydb`.`Protein` (`Accesion_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Protein_has_PTM_PTM1`
    FOREIGN KEY (`PTM_PTM_ID`)
    REFERENCES `mydb`.`PTM` (`PTM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domain_has_Protein`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domain_has_Protein` (
  `Domain_Domain_ID` INT NOT NULL,
  `Protein_Accesion_ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Domain_Domain_ID`, `Protein_Accesion_ID`),
  INDEX `fk_Domain_has_Protein_Protein1_idx` (`Protein_Accesion_ID` ASC) VISIBLE,
  INDEX `fk_Domain_has_Protein_Domain1_idx` (`Domain_Domain_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Domain_has_Protein_Domain1`
    FOREIGN KEY (`Domain_Domain_ID`)
    REFERENCES `mydb`.`Domain` (`Domain_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Domain_has_Protein_Protein1`
    FOREIGN KEY (`Protein_Accesion_ID`)
    REFERENCES `mydb`.`Protein` (`Accesion_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
