"""Fix graph column type

Revision ID: 5d1941bfb60c
Revises: 
Create Date: 2025-03-21 18:55:18.382470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1941bfb60c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.alter_column('graph',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.alter_column('graph',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
